# Generated by Django 4.1.7 on 2023-02-19 01:13

from django.db import migrations, models
import django.db.models.deletion
import questions.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='名称')),
                ('notes', models.TextField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='questions.clasf', verbose_name='上级')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=512, unique=True, verbose_name='题目')),
                ('types', models.SmallIntegerField(verbose_name='类型')),
                ('answers', models.CharField(max_length=256, verbose_name='答项')),
                ('answer', models.CharField(max_length=32, verbose_name='正确答案')),
                ('flag', models.CharField(blank=True, max_length=64, null=True)),
                ('notes', models.TextField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('en', models.BooleanField(default=True, verbose_name='启用')),
                ('score', models.SmallIntegerField(verbose_name='分数')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('clasf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questions.clasf', verbose_name='分类')),
                ('docker_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='practices.dockerimages', verbose_name='docker镜像')),
            ],
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to=questions.models.upload_path)),
                ('name', models.CharField(max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('notes', models.TextField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attaches', to='questions.questions', verbose_name='题库')),
            ],
        ),
    ]
