# Generated by Django 4.1.7 on 2023-02-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='正确答案'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answers',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='答项'),
        ),
    ]
