# Generated by Django 4.1.7 on 2023-03-01 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_questions_answer_alter_questions_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='docker_image',
        ),
    ]
