# Generated by Django 4.1.7 on 2023-03-09 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_remove_questions_docker_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='flag',
        ),
    ]
