# Generated by Django 4.1.7 on 2023-03-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_answers_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=models.CharField(max_length=512, verbose_name='值'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='value',
            field=models.CharField(max_length=512, verbose_name='值'),
        ),
    ]
