# Generated by Django 4.1.7 on 2023-03-13 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_answer_value_alter_answers_value'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('qs', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='answers',
            unique_together={('qs', 'value')},
        ),
    ]
