# Generated by Django 4.1.7 on 2023-03-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_answer_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='删除'),
        ),
    ]
