# Generated by Django 4.1.7 on 2023-03-13 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_questions_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='delete',
            new_name='is_delete',
        ),
    ]
