# Generated by Django 4.1.7 on 2023-03-16 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0009_remove_dockerimages_qs'),
        ('questions', '0009_rename_delete_questions_is_delete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['-create_at']},
        ),
        migrations.AddField(
            model_name='questions',
            name='docker_images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='practices.dockerimages', verbose_name='docker镜像'),
        ),
    ]
