# Generated by Django 4.1.7 on 2023-03-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_alter_answer_qs_alter_answers_qs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=1024, null=True, verbose_name='备注'),
        ),
    ]
