# Generated by Django 4.1.7 on 2023-03-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_alter_questions_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='notes',
            field=models.TextField(default='', max_length=1024, null=True, verbose_name='备注'),
        ),
    ]
