# Generated by Django 4.1.7 on 2023-02-19 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DockerImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=128, verbose_name='镜像ID')),
                ('notes', models.CharField(blank=True, max_length=2048, null=True, verbose_name='说明')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='DockerContainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='名称')),
                ('uid', models.CharField(max_length=32, verbose_name='用户ID')),
                ('cid', models.CharField(max_length=32, verbose_name='容器ID')),
                ('qid', models.IntegerField(verbose_name='题库ID')),
                ('status', models.SmallIntegerField(verbose_name='状态')),
                ('hostport', models.IntegerField(verbose_name='主机端口')),
                ('port', models.IntegerField(verbose_name='容器端口')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='practices.dockerimages')),
            ],
        ),
    ]
