# Generated by Django 4.1.7 on 2023-02-28 01:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0002_dockerimages_cport_alter_dockerimages_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockercontainers',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
    ]
