# Generated by Django 4.1.7 on 2023-03-01 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_remove_questions_docker_image'),
        ('practices', '0003_dockercontainers_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dockerimages',
            name='image_id',
        ),
        migrations.AddField(
            model_name='dockerimages',
            name='qs',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='docker_image', to='questions.questions', verbose_name='赛题'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dockerimages',
            name='short_id',
            field=models.CharField(default='', max_length=64, verbose_name='镜像ID'),
            preserve_default=False,
        ),
    ]
