# Generated by Django 4.1.7 on 2023-03-01 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0004_remove_dockerimages_image_id_dockerimages_qs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dockerimages',
            old_name='short_id',
            new_name='imageid',
        ),
    ]
