# Generated by Django 4.1.7 on 2023-03-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0005_rename_short_id_dockerimages_imageid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dockercontainers',
            name='uid',
        ),
        migrations.AddField(
            model_name='dockercontainers',
            name='uname',
            field=models.CharField(default='', max_length=32, verbose_name='账号'),
            preserve_default=False,
        ),
    ]
