# Generated by Django 4.1.7 on 2023-03-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0006_remove_dockercontainers_uid_dockercontainers_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerimages',
            name='imagename',
            field=models.CharField(default='', max_length=64, verbose_name='镜像名称'),
            preserve_default=False,
        ),
    ]
