# Generated by Django 4.1.7 on 2023-03-01 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0007_dockerimages_imagename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dockerimages',
            old_name='imagename',
            new_name='name',
        ),
    ]
