# Generated by Django 4.1.7 on 2023-03-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0009_remove_dockerimages_qs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockerimages',
            name='imageid',
            field=models.CharField(max_length=64, unique=True, verbose_name='镜像ID'),
        ),
    ]
