# Generated by Django 4.1.7 on 2023-02-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='level',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='级别'),
        ),
    ]
