# Generated by Django 4.1.7 on 2023-02-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_group_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='level',
            field=models.SmallIntegerField(blank=True, null=True, unique=True, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='名称'),
        ),
    ]
