# Generated by Django 4.1.7 on 2023-02-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_group_level_alter_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=35, verbose_name='昵称'),
        ),
    ]
