# Generated by Django 4.1.7 on 2023-02-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, related_name='user', to='accounts.roles', verbose_name='角色'),
        ),
    ]
