# Generated by Django 4.1.7 on 2023-02-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='level',
            field=models.SmallIntegerField(default=0, unique=True, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='group',
            name='notes',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='level',
            field=models.SmallIntegerField(default=0, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='user', to='accounts.roles', verbose_name='角色'),
        ),
    ]
