# Generated by Django 4.1.7 on 2023-02-17 03:22

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_group_level_alter_group_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notes',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=32, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
