# Generated by Django 4.1.7 on 2023-02-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_notes_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='icon',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='accountIcons/', verbose_name='图标'),
        ),
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='accountIcons/', verbose_name='图标'),
        ),
    ]
