# Generated by Django 4.1.7 on 2023-02-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_group_icon_user_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, default='', max_length=256, null=True, upload_to='accountIcons/', verbose_name='图标'),
        ),
    ]
