# Generated by Django 4.1.7 on 2023-02-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='level',
            field=models.SmallIntegerField(default=0, verbose_name='级别'),
        ),
    ]
