# Generated by Django 4.1.7 on 2023-02-19 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('accounts', '0008_group_icon_user_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True, verbose_name='名称')),
                ('notes', models.TextField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('starttime', models.DateTimeField(verbose_name='开始时间')),
                ('endtime', models.DateTimeField(verbose_name='结束时间')),
                ('groups', models.ManyToManyField(blank=True, related_name='cometitions', to='accounts.group', verbose_name='队伍')),
                ('questions', models.ManyToManyField(blank=True, related_name='+', to='questions.questions', verbose_name='题库')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField(blank=True, null=True)),
                ('score', models.SmallIntegerField(blank=True, null=True, verbose_name='分数')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competitions.competitions')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.questions', verbose_name='题库')),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='答题人')),
            ],
        ),
    ]
