# Generated by Django 4.1.7 on 2023-03-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_answerrecords_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerrecords',
            name='gid',
            field=models.IntegerField(blank=True, null=True, verbose_name='队伍id'),
        ),
    ]
