# Generated by Django 4.1.7 on 2023-03-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_answerrecords_handed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerrecords',
            name='answer',
            field=models.JSONField(default=[], verbose_name='答案'),
        ),
    ]
