# Generated by Django 4.1.7 on 2023-03-15 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_alter_answerrecords_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerrecords',
            options={'ordering': ['-create_at']},
        ),
        migrations.AlterModelOptions(
            name='competitions',
            options={'ordering': ['-create_at']},
        ),
        migrations.AddField(
            model_name='competitions',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
    ]
