# Generated by Django 4.1.7 on 2023-03-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_alter_answerrecords_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerrecords',
            name='answer',
            field=models.JSONField(default=list, verbose_name='答案'),
        ),
    ]
