# Generated by Django 4.1.7 on 2023-03-22 01:17

import competitions.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0010_alter_answerrecords_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField(blank=True, null=True, verbose_name='队伍id')),
                ('notes', models.TextField(default='', max_length=10000, verbose_name='备注')),
                ('files', models.FileField(upload_to=competitions.models.upload_path)),
                ('name', models.CharField(max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competitions.competitions')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='答题人')),
            ],
        ),
    ]
