# Generated by Django 4.1.7 on 2023-03-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_writeup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeup',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
