# Generated by Django 4.1.7 on 2023-04-04 08:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0012_alter_writeup_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='writeup',
            unique_together={('competition', 'respondent')},
        ),
    ]
